// Generated from teacup icons package
// Source: https://github.com/mistakenelf/teacup/tree/main/icons

import { IconSet, IconDef } from "./glyphs.js";

/**
 * Icon mappings for file extensions.
 * @public
 */
export const IconExt = {
  "4th": IconDef.file, // "forth" not available
  "7z": IconSet["zip"],
  "a51": IconSet["assembly"],
  "abc": IconDef.file, // "abc" not available
  "ac": IconSet["3d"],
  "accdb": IconSet["database"],
  "ad": IconSet["asciidoc"],
  "adoc": IconSet["asciidoc"],
  "aea": IconSet["assembly"],
  "afphoto": IconSet["image"],
  "agc": IconSet["assembly"],
  "ags": IconSet["assembly"],
  "ahk": IconSet["autohotkey"],
  "aiff": IconSet["audio"],
  "ami": IconSet["image"],
  "amx": IconSet["pawn"],
  "apib": IconSet["apiblueprint"],
  "apiblueprint": IconSet["apiblueprint"],
  "apk": IconSet["android"],
  "applescript": IconSet["applescript"],
  "apx": IconSet["image"],
  "argus": IconSet["assembly"],
  "as": IconSet["actionscript"],
  "asc": IconSet["key"],
  "asciidoc": IconSet["asciidoc"],
  "ase": IconSet["image"],
  "aseprite": IconSet["image"],
  "asm": IconSet["assembly"],
  "asp": IconSet["html"],
  "ast": IconDef.file, // "sas" not available
  "astore": IconDef.file, // "sas" not available
  "au3": IconDef.file, // "autoit" not available
  "avi": IconSet["video"],
  "awk": IconSet["console"],
  "azcli": IconSet["azure"],
  "bal": IconDef.file, // "ballerina" not available
  "balx": IconDef.file, // "ballerina" not available
  "bash": IconSet["console"],
  "bat": IconSet["console"],
  "bazel": IconDef.file, // "bazel" not available
  "bib": IconSet["lib"],
  "binsource": IconSet["assembly"],
  "blend": IconSet["3d"],
  "blink": IconSet["blink"],
  "bmap": IconSet["font"],
  "bmp": IconSet["image"],
  "bpg": IconSet["image"],
  "br": IconSet["zip"],
  "brk": IconSet["image"],
  "brotli": IconSet["zip"],
  "bzip2": IconSet["zip"],
  "bzl": IconDef.file, // "bazel" not available
  "c": IconSet["c"],
  "c++": IconSet["cpp"],
  "cabal": IconDef.file, // "cabal" not available
  "cake": IconSet["cake"],
  "cc": IconSet["cpp"],
  "cer": IconSet["certificate"],
  "cert": IconSet["certificate"],
  "cfc": IconDef.file, // "coldfusion" not available
  "cfg": IconSet["settings"],
  "cfm": IconDef.file, // "coldfusion" not available
  "cfml": IconDef.file, // "coldfusion" not available
  "ch": IconDef.file, // "advpl_include" not available
  "cl": IconDef.file, // "lisp" not available
  "clip": IconSet["image"],
  "clj": IconSet["clojure"],
  "cljc": IconSet["clojure"],
  "cljs": IconSet["clojure"],
  "cm": IconDef.file, // "sml" not available
  "cmake": IconSet["cmake"],
  "cmd": IconSet["console"],
  "cmj": IconDef.file, // "bucklescript" not available
  "cmx": IconSet["ocaml"],
  "coco": IconSet["coconut"],
  "code-workplace": IconSet["vscode"],
  "coffee": IconSet["coffee"],
  "command": IconSet["command"],
  "conf": IconSet["settings"],
  "config": IconSet["settings"],
  "cp": IconSet["cpp"],
  "cpp": IconSet["cpp"],
  "cpt": IconSet["image"],
  "cr": IconDef.file, // "crystal" not available
  "crt": IconSet["certificate"],
  "cs": IconSet["csharp"],
  "csh": IconSet["console"],
  "cshtml": IconSet["razor"],
  "cson": IconSet["coffee"],
  "csproj": IconSet["visualstudio"],
  "css": IconSet["css"],
  "csv": IconSet["table"],
  "csx": IconSet["csharp"],
  "cu": IconDef.file, // "cuda" not available
  "cuh": IconDef.file, // "cuda" not available
  "cur": IconSet["image"],
  "cxx": IconSet["cpp"],
  "d": IconSet["d"],
  "dart": IconSet["dart"],
  "dds": IconSet["image"],
  "deb": IconSet["debian"],
  "def": IconDef.file, // "dotjs" not available
  "dhall": IconSet["dhall"],
  "dhallb": IconSet["dhall"],
  "dio": IconDef.file, // "drawio" not available
  "djt": IconSet["django"],
  "dlc": IconSet["settings"],
  "dll": IconSet["settings"],
  "dng": IconSet["image"],
  "doc": IconSet["word"],
  "dockerfile": IconSet["docker"],
  "dockerignore": IconSet["docker"],
  "docx": IconSet["word"],
  "dot": IconDef.file, // "dotjs" not available
  "dotsettings": IconSet["settings"],
  "drawio": IconDef.file, // "drawio" not available
  "dsc": IconSet["denizenscript"],
  "dtd": IconSet["xml"],
  "dtx": IconSet["tex"],
  "ebuild": IconSet["gentoo"],
  "ecr": IconDef.file, // "crystal" not available
  "edge": IconSet["edge"],
  "eex": IconSet["elixir"],
  "ejs": IconSet["ejs"],
  "elm": IconSet["elm"],
  "env": IconSet["tune"],
  "eot": IconSet["font"],
  "eps": IconSet["image"],
  "erb": IconSet["ruby"],
  "erl": IconSet["erlang"],
  "esx": IconSet["javascript"],
  "ex": IconSet["elixir"],
  "exe": IconSet["exe"],
  "exr": IconSet["image"],
  "exrc": IconSet["vim"],
  "exs": IconSet["elixir"],
  "f": IconSet["fortran"],
  "f03": IconSet["fortran"],
  "f08": IconSet["fortran"],
  "f77": IconSet["fortran"],
  "f90": IconSet["fortran"],
  "f95": IconSet["fortran"],
  "fast": IconDef.file, // "lisp" not available
  "feature": IconDef.file, // "cucumber" not available
  "fhtml": IconDef.file, // "velocity" not available
  "fish": IconSet["console"],
  "flac": IconSet["audio"],
  "flv": IconSet["video"],
  "fnt": IconSet["font"],
  "font": IconSet["font"],
  "fonts": IconSet["font"],
  "fpx": IconSet["image"],
  "frt": IconDef.file, // "forth" not available
  "fs": IconSet["fsharp"],
  "fsi": IconSet["fsharp"],
  "fsproj": IconSet["fsharp"],
  "fsx": IconSet["fsharp"],
  "fth": IconDef.file, // "forth" not available
  "fun": IconDef.file, // "sml" not available
  "fxp": IconDef.file, // "foxpro" not available
  "gbr": IconSet["image"],
  "gd": IconSet["godot"],
  "gif": IconSet["image"],
  "gifv": IconSet["video"],
  "go": IconSet["go"],
  "godot": IconSet["godot-assets"],
  "gpg": IconSet["key"],
  "gql": IconSet["graphql"],
  "gradle": IconSet["gradle"],
  "graphcool": IconDef.file, // "graphcool" not available
  "graphql": IconSet["graphql"],
  "grm": IconDef.file, // "sml" not available
  "groovy": IconSet["groovy"],
  "gvimrc": IconSet["vim"],
  "gz": IconSet["zip"],
  "gzip": IconSet["zip"],
  "h": IconSet["h"],
  "h++": IconSet["hpp"],
  "haml": IconDef.file, // "haml" not available
  "hbs": IconSet["handlebars"],
  "hcl": IconDef.file, // "hcl" not available
  "heic": IconSet["image"],
  "heif": IconSet["image"],
  "hh": IconSet["hpp"],
  "hp": IconSet["hpp"],
  "hpp": IconSet["hpp"],
  "hs": IconSet["haskell"],
  "htm": IconSet["html"],
  "html": IconSet["html"],
  "html_vm": IconSet["html"],
  "http": IconSet["http"],
  "hx": IconSet["haxe"],
  "hxx": IconSet["hpp"],
  "i": IconSet["c"],
  "iced": IconSet["coffee"],
  "ico": IconSet["image"],
  "ics": IconSet["email"],
  "ii": IconSet["cpp"],
  "imba": IconDef.file, // "imba" not available
  "img": IconSet["image"],
  "iml": IconSet["xml"],
  "inc": IconSet["assembly"],
  "ini": IconSet["settings"],
  "inl": IconSet["hpp"],
  "ino": IconSet["arduino"],
  "ipa": IconSet["applescript"],
  "ipynb": IconDef.file, // "jupyter" not available
  "iso": IconSet["disc"],
  "iuml": IconDef.file, // "uml" not available
  "j2": IconSet["jinja"],
  "jade": IconSet["pug"],
  "jar": IconSet["java"],
  "java": IconSet["java"],
  "jb2": IconSet["image"],
  "jbig2": IconSet["image"],
  "jenkins": IconSet["jenkins"],
  "jenkinsfile": IconSet["jenkins"],
  "jinja": IconSet["jinja"],
  "jinja-html": IconSet["jinja"],
  "jinja2": IconSet["jinja"],
  "jl": IconSet["julia"],
  "jng": IconSet["image"],
  "jpeg": IconSet["image"],
  "jpg": IconSet["image"],
  "js": IconSet["javascript"],
  "json": IconSet["json"],
  "json5": IconSet["json"],
  "jsonl": IconSet["json"],
  "jsp": IconSet["java"],
  "jst": IconDef.file, // "dotjs" not available
  "jsx": IconSet["react"],
  "jxr": IconSet["image"],
  "key": IconSet["key"],
  "kl": IconDef.file, // "kl" not available
  "kra": IconSet["image"],
  "ksh": IconSet["console"],
  "kt": IconSet["kotlin"],
  "kts": IconSet["kotlin"],
  "kv": IconDef.file, // "kivy" not available
  "leex": IconSet["elixir"],
  "less": IconSet["less"],
  "lex": IconDef.file, // "sml" not available
  "lib": IconSet["lib"],
  "liquid": IconSet["liquid"],
  "lisp": IconDef.file, // "lisp" not available
  "lock": IconSet["lock"],
  "log": IconSet["log"],
  "ls": IconDef.file, // "livescript" not available
  "lsp": IconDef.file, // "lisp" not available
  "ltx": IconSet["tex"],
  "lua": IconSet["lua"],
  "lucee": IconDef.file, // "coldfusion" not available
  "m": IconSet["c"],
  "m2v": IconSet["video"],
  "m4a": IconSet["audio"],
  "m4v": IconSet["video"],
  "manifest": IconSet["xml"],
  "markdown": IconSet["markdown"],
  "marko": IconSet["markojs"],
  "md": IconSet["markdown"],
  "mdb": IconSet["database"],
  "mdp": IconSet["image"],
  "mdx": IconSet["mdx"],
  "merlin": IconSet["merlin"],
  "mesh": IconSet["3d"],
  "mi": IconSet["c"],
  "mii": IconSet["cpp"],
  "mint": IconSet["mint"],
  "mitigus": IconSet["assembly"],
  "mj": IconSet["javascript"],
  "mjml": IconSet["mjml"],
  "mkv": IconSet["video"],
  "ml": IconSet["ocaml"],
  "mlb": IconDef.file, // "sml" not available
  "mli": IconSet["ocaml"],
  "mlton": IconDef.file, // "sml" not available
  "mm": IconSet["cpp"],
  "mo": IconSet["i18n"],
  "moon": IconSet["moonscript"],
  "mov": IconSet["video"],
  "mp2": IconSet["video"],
  "mp3": IconSet["audio"],
  "mp4": IconSet["video"],
  "mpe": IconSet["video"],
  "mpeg": IconSet["video"],
  "mpg": IconSet["video"],
  "mpv": IconSet["video"],
  "mqo": IconSet["3d"],
  "mrf": IconSet["font"],
  "ms": IconSet["assembly"],
  "msi": IconSet["exe"],
  "mustache": IconSet["handlebars"],
  "mxml": IconSet["mxml"],
  "nasm": IconSet["assembly"],
  "nb": IconDef.file, // "mathematica" not available
  "ndjson": IconSet["json"],
  "nim": IconSet["nim"],
  "nimble": IconSet["nim"],
  "nix": IconSet["nix"],
  "njk": IconDef.file, // "nunjucks" not available
  "ntf": IconSet["font"],
  "nunjucks": IconDef.file, // "nunjucks" not available
  "nupkg": IconSet["nuget"],
  "obj": IconSet["3d"],
  "odttf": IconSet["font"],
  "ogg": IconSet["video"],
  "ogv": IconSet["video"],
  "opam": IconSet["opam"],
  "openbsd": IconSet["freebsd"],
  "option": IconSet["settings"],
  "ora": IconSet["image"],
  "otf": IconSet["font"],
  "p": IconSet["prolog"],
  "pas": IconSet["pascal"],
  "patch": IconSet["git"],
  "pbm": IconSet["image"],
  "pcss": IconSet["postcss"],
  "pdb": IconSet["database"],
  "pde": IconDef.file, // "processing" not available
  "pdf": IconSet["pdf"],
  "pdn": IconSet["image"],
  "pem": IconSet["key"],
  "pgf": IconSet["image"],
  "pgsql": IconSet["postgresql"],
  "pic": IconSet["image"],
  "pkb": IconSet["database"],
  "pkg": IconSet["applescript"],
  "pks": IconSet["database"],
  "plantuml": IconDef.file, // "uml" not available
  "plist": IconSet["xml"],
  "pm": IconSet["perl"],
  "pmd": IconSet["3d"],
  "pmx": IconSet["3d"],
  "png": IconSet["image"],
  "po": IconSet["i18n"],
  "postgres": IconSet["postgresql"],
  "pot": IconSet["i18n"],
  "potm": IconSet["powerpoint"],
  "potx": IconSet["powerpoint"],
  "pp": IconSet["puppet"],
  "ppa": IconSet["powerpoint"],
  "ppam": IconSet["powerpoint"],
  "pps": IconSet["powerpoint"],
  "ppsm": IconSet["powerpoint"],
  "ppsx": IconSet["powerpoint"],
  "ppt": IconSet["powerpoint"],
  "pptm": IconSet["powerpoint"],
  "pptx": IconSet["powerpoint"],
  "prefs": IconSet["settings"],
  "prg": IconDef.file, // "foxpro" not available
  "prisma": IconDef.file, // "prisma" not available
  "pro": IconSet["prolog"],
  "project": IconSet["xml"],
  "prop": IconSet["settings"],
  "properties": IconSet["settings"],
  "props": IconSet["settings"],
  "prw": IconDef.file, // "advpl_prw" not available
  "prx": IconDef.file, // "advpl_prw" not available
  "ps1": IconSet["powershell"],
  "ps1xml": IconSet["powershell"],
  "psb": IconSet["image"],
  "psc1": IconSet["powershell"],
  "psd": IconSet["image"],
  "psd1": IconSet["powershell"],
  "psm1": IconSet["powershell"],
  "psql": IconSet["postgresql"],
  "pssc": IconSet["powershell"],
  "ptm": IconDef.file, // "advpl_ptm" not available
  "pu": IconDef.file, // "uml" not available
  "pub": IconSet["key"],
  "pug": IconSet["pug"],
  "puml": IconDef.file, // "uml" not available
  "pure": IconSet["purescript"],
  "purs": IconSet["purescript"],
  "pwn": IconSet["pawn"],
  "py": IconSet["python"],
  "pyc": IconSet["python-misc"],
  "qs": IconSet["qsharp"],
  "qt": IconSet["video"],
  "r": IconSet["r"],
  "raku": IconSet["perl"],
  "raml": IconSet["raml"],
  "rar": IconSet["zip"],
  "raw": IconSet["image"],
  "rb": IconSet["ruby"],
  "re": IconDef.file, // "reason" not available
  "reb": IconSet["image"],
  "red": IconDef.file, // "red" not available
  "rei": IconDef.file, // "reason" not available
  "rest": IconSet["http"],
  "restql": IconDef.file, // "restql" not available
  "resx": IconSet["xml"],
  "riot": IconDef.file, // "riot" not available
  "rkt": IconDef.file, // "racket" not available
  "rm": IconSet["video"],
  "rmd": IconSet["r"],
  "rmvb": IconSet["video"],
  "robot": IconSet["robot"],
  "rpm": IconSet["redhat"],
  "rql": IconDef.file, // "restql" not available
  "rs": IconSet["rust"],
  "rst": IconSet["markdown"],
  "rtf": IconSet["word"],
  "ruleset": IconSet["visualstudio"],
  "s": IconSet["assembly"],
  "sai": IconSet["image"],
  "san": IconDef.file, // "san" not available
  "sas": IconDef.file, // "sas" not available
  "sas7bdat": IconDef.file, // "sas" not available
  "sashdat": IconDef.file, // "sas" not available
  "sass": IconSet["sass"],
  "sast": IconDef.file, // "sas" not available
  "sbt": IconDef.file, // "sbt" not available
  "scm": IconSet["scheme"],
  "scss": IconSet["sass"],
  "settings": IconSet["settings"],
  "sh": IconSet["console"],
  "sig": IconDef.file, // "sml" not available
  "sketch": IconSet["sketch"],
  "skp": IconSet["3d"],
  "slim": IconSet["slim"],
  "sln": IconSet["visualstudio"],
  "sml": IconDef.file, // "sml" not available
  "snap": IconSet["ubuntu"],
  "sol": IconSet["solidity"],
  "sql": IconSet["mysql"],
  "sqlite": IconSet["sqlite"],
  "sqlite3": IconSet["sqlite"],
  "ss": IconSet["scheme"],
  "sss": IconSet["postcss"],
  "stl": IconSet["3d"],
  "sty": IconSet["tex"],
  "styl": IconSet["stylus"],
  "sublime-project": IconSet["sublime"],
  "sublime-workspace": IconSet["sublime"],
  "sui": IconSet["font"],
  "suit": IconSet["font"],
  "suo": IconSet["visualstudio"],
  "sv": IconSet["verilog"],
  "svelte": IconDef.file, // "svelte" not available
  "svg": IconSet["svg"],
  "svh": IconSet["verilog"],
  "swc": IconSet["swc"],
  "swf": IconSet["flash"],
  "swift": IconSet["swift"],
  "tag": IconDef.file, // "riot" not available
  "tar": IconSet["zip"],
  "tcc": IconSet["hpp"],
  "tcl": IconSet["tcl"],
  "tcsh": IconSet["console"],
  "tex": IconSet["tex"],
  "tf": IconSet["terraform"],
  "tfstate": IconSet["terraform"],
  "tfvars": IconSet["terraform"],
  "tga": IconSet["image"],
  "tgz": IconSet["zip"],
  "tif": IconSet["image"],
  "tiff": IconSet["image"],
  "tlpp": IconDef.file, // "advpl_tlpp" not available
  "tmLanguage": IconSet["xml"],
  "todo": IconSet["todo"],
  "toml": IconSet["settings"],
  "tpl": IconSet["smarty"],
  "tres": IconSet["godot-assets"],
  "ts": IconSet["typescript"],
  "tsbuildinfo": IconSet["json"],
  "tscn": IconSet["godot-assets"],
  "tsv": IconSet["table"],
  "tsx": IconSet["react_ts"],
  "ttc": IconSet["font"],
  "ttf": IconSet["font"],
  "twig": IconSet["twig"],
  "txt": IconSet["document"],
  "unity": IconSet["shaderlab"],
  "url": IconSet["url"],
  "use": IconDef.file, // "sml" not available
  "v": IconSet["verilog"],
  "vac": IconSet["3d"],
  "vagrantfile": IconSet["vagrant"],
  "vala": IconSet["vala"],
  "vb": IconSet["visualstudio"],
  "vbhtml": IconSet["razor"],
  "vbox": IconSet["virtual"],
  "vbox-prev": IconSet["virtual"],
  "vbs": IconSet["visualstudio"],
  "vcxitems": IconSet["visualstudio"],
  "vcxproj": IconSet["visualstudio"],
  "vdi": IconSet["virtual"],
  "vdp": IconSet["3d"],
  "vfl": IconDef.file, // "vfl" not available
  "vhd": IconSet["verilog"],
  "vimrc": IconSet["vim"],
  "vm": IconDef.file, // "velocity" not available
  "vob": IconSet["video"],
  "vox": IconSet["3d"],
  "vscodeignore": IconSet["vscode"],
  "vsix": IconSet["vscode"],
  "vsixmanifest": IconSet["vscode"],
  "vtl": IconDef.file, // "velocity" not available
  "vue": IconSet["vue"],
  "wasm": IconDef.file, // "webassembly" not available
  "wat": IconDef.file, // "webassembly" not available
  "webm": IconSet["video"],
  "webp": IconSet["image"],
  "whl": IconSet["python-misc"],
  "wl": IconDef.file, // "wolframlanguage" not available
  "wls": IconDef.file, // "wolframlanguage" not available
  "wma": IconSet["audio"],
  "wmv": IconSet["video"],
  "woff": IconSet["font"],
  "woff2": IconSet["font"],
  "wpy": IconDef.file, // "wepy" not available
  "wsd": IconDef.file, // "uml" not available
  "xaml": IconSet["xaml"],
  "xcf": IconSet["image"],
  "xhtml": IconSet["html"],
  "xls": IconSet["table"],
  "xlsx": IconSet["table"],
  "xml": IconSet["xml"],
  "xquery": IconSet["xml"],
  "xsd": IconSet["xml"],
  "xsl": IconSet["xml"],
  "xslt": IconSet["xml"],
  "xz": IconSet["zip"],
  "yaml": IconSet["yaml"],
  "yaml-tmlanguage": IconSet["yaml"],
  "yang": IconSet["yang"],
  "yml": IconSet["yaml"],
  "yuv": IconSet["video"],
  "zig": IconSet["zig"],
  "zip": IconSet["zip"],
  "zsh": IconSet["console"],
} as const;
